version: "2"
services:
  mealie:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mealie
    restart: always
    ports:
      - 9090:80
    volumes:
      - data:/app/data/
    environment:
      db_type: sqlite
volumes:
  data:
